KPI_Project/urls.py
#Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',include(('cases.urls','case'), namespace = 'cases')),
    path('users/',include(('users.urls','users'), namespace = 'users')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cases/urls.py
"""Cases URLS.s"""

#Django
from django.urls import path
from django.views.generic import TemplateView

#views
from cases import views

urlpatterns = [

    # Management
    path(
        route='',
        view=views.CasesFeedView.as_view(),
        name='feed'
    ),

    path(
        route='cases/new/',
        view=views.CasesCreateView.as_view(),
        name='create'
    ),

    path('cases/updatecase/', views.MyUpdateView,name="updatecase"), 

    path(
        route='cases/listcases/',
        view=views.CasesListView.as_view(),
        name='list'
    ),
]

users/urls.py
"""Users URLS.s"""

#Django
from django.urls import path
from django.views.generic import TemplateView

#views
from users import views

urlpatterns = [

    # Management
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),

    path(
        route='profile/',
        view=views.ProfileView.as_view(),
        name='profile'
    ),

    path(
        route='uptateprofile/',
        view=views.UptateProfileView.as_view(),
        name='update_profile'
    ),
    
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main2.css' %}" />
   
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
 
</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}

        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "cases:feed"  %}">
            <img src="{% static "img/materialise.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url "users:profile"  %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "cases:create"  %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "users:logout"  %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>