KPI_Project/urls.py
#Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',include(('cases.urls','case'), namespace = 'cases')),
    path('users/',include(('users.urls','users'), namespace = 'users')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cases/urls.py
"""Cases URLS.s"""

#Django
from django.urls import path
from django.views.generic import TemplateView

#views
from cases import views

urlpatterns = [

    # Management
    path(
        route='',
        view=views.CasesFeedView.as_view(),
        name='feed'
    ),

    path(
        route='cases/new/',
        view=views.CasesCreateView.as_view(),
        name='create'
    ),

    path('cases/updatecase/', views.MyUpdateView,name="updatecase"), 

    path(
        route='cases/listcases/',
        view=views.CasesListView.as_view(),
        name='list'
    ),
]

users/urls.py
"""Users URLS.s"""

#Django
from django.urls import path
from django.views.generic import TemplateView

#views
from users import views

urlpatterns = [

    # Management
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),

    path(
        route='profile/',
        view=views.ProfileView.as_view(),
        name='profile'
    ),

    path(
        route='uptateprofile/',
        view=views.UptateProfileView.as_view(),
        name='update_profile'
    ),
    
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
]

cases/models.py
"""Cases models"""

#Django
from django.db import models
from django.contrib.auth.models import User

class Case(models.Model):
    """Case model"""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    case_id = models.CharField(max_length=12,blank=False,null=False)
    step = models.CharField(max_length=30,blank=False)
    surgery_type = models.CharField(max_length=30,blank=False)
    
    is_qc = models.BooleanField(blank=False)
    is_complex = models.BooleanField(blank=False)

    is_rejected = models.BooleanField(blank=True, null=True)

    time = models.IntegerField(blank=False,null=False)

    created = models.DateTimeField(auto_now_add=True)

    comments = models.CharField(max_length=1000,blank=True)

    def __str__(self):
        """Return case id"""
        return '{}'.format(self.case_id)

cases/forms.py
"""Case forms"""

#Django
from django import forms

#models
from cases.models import Case
from cases import views

class CaseForm(forms.ModelForm):
    """Post model form."""

    class Meta:
        """Form settings"""

        model = Case
        fields = (
                'user',
                'profile',
                'case_id',
                'step',
                'surgery_type',
                'is_qc',
                'is_complex',
                'is_rejected',
                'time',
                'comments'
        )
     

cases/views.py
""" Posts views."""

#Django
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView,ListView, UpdateView
from django.urls import reverse_lazy, reverse
from django import forms
from django.shortcuts import render
from django.contrib import messages

#Models
from cases.models import Case

#Forms
from cases.forms import CaseForm

class CasesFeedView(LoginRequiredMixin,TemplateView):
    template_name = "cases/feed.html"

class CasesListView(LoginRequiredMixin,ListView):
    template_name = "cases/listcases.html"
    model = Case
    ordering = ('created')
    context_object_name = 'cases'

    def get_ordering(self):
        
        selected_ordering = self.request.GET.get('ordering', 'created')
        if self.order == "desc":
            selected_ordering = "-" + selected_ordering
        return selected_ordering

    def get_context_data(self,*args,**kwards):
        context = super(CasesListView,self).get_context_data(*args,**kwards)
        context['current_order'] = self.get_ordering()
        context['order'] = self.order
        return context

class CasesCreateView(LoginRequiredMixin, CreateView):
    """Create new post-view"""

    template_name = "cases/new.html"
    form_class = CaseForm
    success_url = reverse_lazy('cases:feed')

    def get_context_data(self,**kwargs):
        """Add user and profile to conext"""
        
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile
        return context

def MyUpdateView(request):
    if request.method == 'POST' and 'update' in request.POST:
        
        case_id = request.POST['case_id']
        
        try:
            case = Case.objects.filter(case_id=case_id).last()
            
            if case:
            
                usercase = case.user
                userrequest = request.user

                if usercase == userrequest:
                    data = request.POST
                    case.step = data['step']
                    case.surgery_type = data['surgery_type']
                    case.is_qc = data['is_qc']
                    case.is_complex = data['is_complex']
                    case.time = data['time']
                    case.is_rejected = data['is_rejected']
                    case.comments = data['comments']
                    case.save()
                    messages.success(request, 'Updated successfully!')  
                else:
                    messages.error(request, "Case ID not found, Try again!")
            else:
                messages.error(request, "Case ID not found, Try again!")

        except:
            messages.error(request, "Case ID not found, Try again!")
            
    elif request.method == 'POST' and 'delete' in request.POST:
        case_id = request.POST['case_id']
        
        try:
            case = Case.objects.filter(case_id=case_id).last()
            
            if case:
            
                usercase = case.user
                userrequest = request.user

                if usercase == userrequest:
                    case.delete()
                    messages.success(request, 'DELETE successfully!') 
                else:
                    messages.error(request, "Case ID not found, Try again!") 
            else:
                messages.error(request, "Case ID not found, Try again!")
                
        except:
            messages.error(request, "Case ID not found, Try again!")

    elif request.method == 'POST' and 'search' in request.POST:

        case_id = request.POST['case_id']

        try:
            case = Case.objects.filter(case_id=case_id).last()
            
            if case:
            
                usercase = case.user
                userrequest = request.user

                if usercase == userrequest:
        
                    return render(request, 'cases/updatecase.html',
                                {
                                'case_id': case.case_id,
                                'step': case.step,
                                'surgery_type': case.surgery_type,
                                'is_qc': case.is_qc,
                                'is_complex': case.is_complex,
                                'time': case.time,
                                'is_rejected': case.is_rejected,
                                'comments': case.comments
                                }
                    )
                    
                else:
                    messages.error(request, "Case ID not found, Try again!")
            else:
                messages.error(request, "Case ID not found, Try again!")
                
        except:
            messages.error(request, "Case ID not found, Try again!")
        
    return render(request, 'cases/updatecase.html')

  

templates/cases/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>KPI</title>
{% endblock%}

{% block container %}

<div   class="container h-100">
    <div class="row h-100 justify-content-center align-items-center" id="box-feed">
        <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
            <div class="row">
                <h2>What do you want to do?</h2>
            </div>
            <form action="{% url "users:profile" %}">
                <div class="row">
                    <button class="btn btn-primary btn-block mt-5" type="submit">My profile</button>
                </div>
            </form>
            
            <form action="{% url "cases:create" %}">
                <div class="row">
                    <button  class="btn btn-primary btn-block mt-5" type="submit">Create case</button>
                </div>
            </form>
            <form action="{% url "cases:updatecase" %}">
                <div class="row">
                    <button  class="btn btn-primary btn-block mt-5" type="submit">Update Case</button>
                </div>
            </form>
            <form action="{% url "cases:list" %}">
                <div class="row">
                    <button  class="btn btn-primary btn-block mt-5" type="submit">All my cases</button>
                </div>
            </form>
            <form action="{% url "users:signup" %}">
                <div class="row">
                    <button class="btn btn-primary btn-block mt-5" type="submit">My KPI</button>
                </div>
            </form>
            
        </div>
    </div>
</div>

{% endblock %}

templates/cases/listcases.html
{% extends "base.html" %}

{% block head_content %}
    <title>List of cases</title>
{% endblock%}
<!DOCTYPE html>
{% block container %}
    <div id="box-feed">
        <table class="table" >
            
            <tr class="table-primary">
                <th scope="col">Case</th>
                <th scope="col">Step<a href="{% url 'cases:list' %}?ordering=step&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">▼</a></th>
                <th scope="col">Surgery type<a href="{% url 'cases:list' %}?ordering=surgery_type&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">▼</a></th>
                <th scope="col">QC?<a href="{% url 'cases:list' %}?ordering=is_qc&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">▼</a></th>
                <th scope="col">Complex?</th>
                <th scope="col">Rejected?</th>
                <th scope="col">Time<a href="{% url 'cases:list' %}?ordering=time&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">▼</a></th>
                <th scope="col">Comments</th>
                <th scope="col">Created <a href="{% url 'cases:list' %}?ordering=created&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">▼</a></th>
            </tr>
            </thead>
            <tbody>
            {% for case in cases %}
                {% if user.username == case.user.username %}    
                    <tr>
                        <td>{{case.case_id}}</td>
                        <td>{{case.step}}</td>
                        <td>{{case.surgery_type}}</td>
                        <td>{{case.is_qc}}</td>
                        <td>{{case.is_complex}}</td>
                        <td>{{case.is_rejected}}</td>
                        <td>{{case.time}}</td>
                        <td>{{case.comments}}</td>
                        <td>{{case.created}}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    
{% endblock %}

templates/cases/new.html
{% extends "base.html" %}

{% block head_content %}
    <title>Create new case</title>
{% endblock %}
<!DOCTYPE html>
{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Store a new case!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
  
                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}"/>
                    
                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.case_id.errors %}is-invalid{% endif %}"
                            type="text"
                            name="case_id"
                            placeholder="Case ID"
                            onkeyup="this.value = this.value.toUpperCase();"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.caseid.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <div class="form-group">
                        <select  
                            class="browser-default custom-select"
                            name="step"
                        >
                            <option selected="">Step</option>
                            <option value="Segmentation">Segmentation</option>
                            <option value="Desing">Desing</option>
                        </select>
                        <div class="invalid-feedback">
                            {% for error in form.caseid.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <div class="form-group">
                        <select  
                            class="browser-default custom-select"
                            name="surgery_type"
                        >
                            <option selected="">Surgery type</option>
                            <option value="Orthognatic">Orthognatic</option>
                            <option value="Reconstruction">Reconstruction</option>
                            <option value="PSI">PSI</option>
                            <option value="Other">Other</option>
                        </select>
                        
                    </div>

                    <div class="form-group">
                        <select  
                            class="browser-default custom-select"
                            name="is_qc"
                        >
                            <option selected="">Is it a QC?</option>
                            <option value="True">YES</option>
                            <option value="False">NO</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <select  
                            class="browser-default custom-select"
                            name="is_complex"
                        >
                            <option selected="">Is it a Complex Case?</option>
                            <option value="True">YES</option>
                            <option value="False">NO</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <input
                            class="form-control {% if form.time.errors %}is-invalid{% endif %}"
                            type="number"
                            name="time"
                            placeholder="Time Required"
                        >
                                                    
                        <div class="invalid-feedback">
                            {% for error in form.time.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <div class="form-group">
                        <input
                            class="form-control {% if form.comments.errors %}is-invalid{% endif %}"
                            type="text"
                            name="comments"
                            placeholder="Comments"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.caseid.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>


                    <button type="submit" class="btn btn-primary btn-block mt-5">Store!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/cases/updatecase.html
{% extends "base.html" %}

{% block head_content %}
    <title>Update Case</title>
{% endblock %}
<!DOCTYPE html>
{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Update Case</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    
                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}"/>
                    
                    {# Website field #}
                    <div class="form-group">
                        <input
                            required
                            class="form-control {% if form.case_id.errors %}is-invalid{% endif %}"
                            type="text"
                            name="case_id"
                            id="case_id"
                            placeholder="Case IDs"
                            onkeyup="this.value = this.value.toUpperCase();"
                            {% if case_id %}
                                value = {{ case_id }}
                            {% endif %} 

                        >
                        
                        {% if messages %}
                       
                            {% for message in messages %}
                                {% if message.tags == "error" %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ message }}
                                    </div>
                                {% endif %} 
                                {% if message.tags == "success" %}
                                    <div class="alert alert-success" role="alert">
                                        {{ message }}
                                    </div>
                                {% endif %}    
                            {% endfor %}
                        
                        {% endif %}
                        
                        {% if comments %}
                            <div class="list-group">
                                <a class="list-group-item list-group-item-success">
                                Store data: {{ case_id }}
                                </a>
                                <a class="list-group-item list-group-item-action">Case Step: {{step}}</a>
                                <a class="list-group-item list-group-item-action">Surgery Type: {{surgery_type}}</a>
                                <a class="list-group-item list-group-item-action">Is it a QC? {{is_qc}}</a>
                                <a class="list-group-item list-group-item-action">Is it complex? {{is_complex}}</a>
                                <a class="list-group-item list-group-item-action">Time: {{time}}</a>
                                <a class="list-group-item list-group-item-action">Is it rejected? {{is_rejected}}</a>
                                <a class="list-group-item list-group-item-action">Comments: {{comments}}</a>
                                
                            </div>
                        {% endif %}

                        <button type="submit" class="btn btn-outline-primary" name="search" >Search</button>
                        <div class="invalid-feedback">
                            {% for error in form.case_id.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <div class="form-group">
                        <select 
                            required
                            class="browser-default custom-select"
                            name="step"
                            
                        >
                            <option selected="">Steps</option>
                            <option value="Segmentation">Segmentation</option>
                            <option value="Desing">Desing</option>
                        </select>
                        <div class="invalid-feedback">
                            {% for error in form.caseid.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <div class="form-group">
                        <select  
                            class="browser-default custom-select"
                            name="surgery_type"
                        >
                            <option selected="">Surgery type</option>
                            <option value="Orthognatic">Orthognatic</option>
                            <option value="Reconstruction">Reconstruction</option>
                            <option value="PSI">PSI</option>
                            <option value="Other">Other</option>
                        </select>
                        
                    </div>

                    <div class="form-group">
                        <select  
                            class="browser-default custom-select"
                            name="is_qc"
                        >
                            <option selected="">Is it a QC?</option>
                            <option value="True">YES</option>
                            <option value="False">NO</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <select  
                            class="browser-default custom-select"
                            name="is_complex"
                        >
                            <option selected="">Is it a Complex Case?</option>
                            <option value="True">YES</option>
                            <option value="False">NO</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <input
                            class="form-control {% if form.time.errors %}is-invalid{% endif %}"
                            type="number"
                            name="time"
                            placeholder="Time Required"
                        >
                                                    
                        <div class="invalid-feedback">
                            {% for error in form.time.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <select  
                            class="browser-default custom-select"
                            name="is_rejected"
                        >
                            <option selected="">Rejected?</option>
                            <option value="True">YES</option>
                            <option value="False">NO</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <input
                            class="form-control {% if form.comments.errors %}is-invalid{% endif %}"
                            type="text"
                            name="comments"
                            placeholder="Comments"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.caseid.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>
                
                    <button type="submit" class="btn btn-primary btn-block mt-5" name="update">Update</button>
                    <button type="submit" class="btn btn-danger btn-block" name="delete" >Delete</button>

                </form>
            </div>
        </div>
    </div>

{% endblock %}