KPI_Project/urls.py
#Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',include(('cases.urls','case'), namespace = 'cases')),
    path('users/',include(('users.urls','users'), namespace = 'users')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cases/urls.py
"""Cases URLS.s"""

#Django
from django.urls import path
from django.views.generic import TemplateView

#views
from cases import views

urlpatterns = [

    # Management
    path(
        route='',
        view=views.CasesFeedView.as_view(),
        name='feed'
    ),

    path(
        route='cases/new/',
        view=views.CasesCreateView.as_view(),
        name='create'
    ),

    path('cases/updatecase/', views.MyUpdateView,name="updatecase"), 

    path(
        route='cases/listcases/',
        view=views.CasesListView.as_view(),
        name='list'
    ),
]

users/urls.py
"""Users URLS.s"""

#Django
from django.urls import path
from django.views.generic import TemplateView

#views
from users import views

urlpatterns = [

    # Management
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),

    path(
        route='profile/',
        view=views.ProfileView.as_view(),
        name='profile'
    ),

    path(
        route='uptateprofile/',
        view=views.UptateProfileView.as_view(),
        name='update_profile'
    ),
    
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
]

users/models.py
"""Users models."""

#Django
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    """ Profile model.

    Proxy model that the extends the base data with other information

    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField( upload_to='users/pictures',blank=True,null=True)
    trained_in = models.CharField(max_length=200, blank = True)

    def __str__(self):
        """Return username."""
        return self.user.username

users/forms.py
"""User forms."""

#Django
from django import forms

#Models
from django.contrib.auth.models import User
from users.models import Profile

class SignupForm(forms.Form):
    """Sign up form"""

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(max_length=50 , widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=50 , widget=forms.PasswordInput())

    first_name = forms.CharField(min_length=4, max_length=50)
    last_name = forms.CharField(min_length=4, max_length=50)

    email = forms.CharField(min_length=1, max_length=50,widget=forms.EmailInput())

    def clean_username(self):
        """ Usename must be unique. """
        
        username = self.cleaned_data['username'] #datos que ya limpio python y que los almacena en un dicconario
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""

        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""

        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
"""Users views."""

#Django
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, DetailView,TemplateView, UpdateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import Profile

#Models
from users.forms import SignupForm
from django.contrib.auth.models import User

class SignupView(FormView):
    """Users sign up view"""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data"""
        form.save()
        return super().form_valid(form)

class ProfileView(LoginRequiredMixin,TemplateView):
    """Profile user view."""

    template_name = 'users/profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

class UptateProfileView(LoginRequiredMixin,UpdateView):
    """Update profile view."""

    template_name = 'users/updateprofile.html'
    model = Profile
    fields = ['picture','trained_in']
    success_url = reverse_lazy('users:profile')

    def get_object(self):
        """Return user`s profile."""
        return self.request.user.profile

class LoginView(auth_views.LoginView):
    """Login view"""

    template_name = 'users/login.html'

class LogoutView(LoginRequiredMixin,auth_views.LogoutView):
    """Logout view."""

    template_name = 'users/logged_out.html'

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main2.css' %}" />

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/materialise.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>KPI Log In</title>
{% endblock %}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger"> 
            Yout username and password did not match please try again
        </p> <!-- clase de bootstrap -->
    {% endif %}
    
    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %} <!-- Token especial de protección contra ataques que trae django -->

        <div class="form-group"> 
            <input type="text" class=form-control placeholder="Username" name="username"> 
        </div>
        
        <div class="form-group"> 
            <input type="password" class=form-control placeholder="Password" name="password"> 
        </div>

        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
        
    </form>  <!-- el action conecta con la url que llamos login en el archivo de urls, apuntando a la ruta que allá pusimos sin importar la ruta solo guiandose por el name -->

    <p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>
{% endblock %}

templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% block head_content %}
    <title>Profile</title>
{% endblock %}
<!DOCTYPE html>

{% block container %}
<div   class="container h-100">
    <div class="row h-100 justify-content-center " id="box-feed">
        <div class="col-sm-12 col-md-5 col-lg-8 ci pt-2 pl-5 pr-5 pb-5" id="auth-container">
            <div class="container" id="profile-name">
                <div class="row justify-content-center">
                    {% if request.user.profile.picture %}
                        <img src="{{ request.user.profile.picture.url }}" height="100" class="d-inline-block rounded-circle"/>
                    {% else %}
                        <img src="{% static 'img/default-profile.png' %}" height="100" class="d-inline-block rounded-circle"/>
                    {% endif %}
                </div>
            </div>            
            
            <div class="row">
                <div class="col-4">
                    <h3>Username</h3>
                </div>
                <div class="col-8" >
                    <h3>@{{ request.user.username }}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <h3>Fist Name: </h3>
                </div>
                <div class="col-8">
                        <h3>{{request.user.first_name}}</h3>
                </div>
            </div>

            <div class="row" >
                <div class="col-4">
                    <h3>Email: </h3>
                </div>
                <div class="col-8">
                        <h3>{{request.user.email}}</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    <h3>Trained in: </h3>
                </div>
                <div class="col-8">
                        <h3>{{user.profile.trained_in}}</h3>
                </div>
            </div>
            
            <form method="get" action="{% url "users:update_profile" %}">
                <button class="btn btn-primary btn-block mt-5" type="submit">Edit Profile</button>
            </form>
            
            
              
        </div>
    </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>KPI Sign In</title>
{% endblock %}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger"> 
            Yout username and password did not match please try again
        </p> <!-- clase de bootstrap -->
    {% endif %}

    <form method="POST" action = "{% url "users:signup" %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
    </form>

{% endblock %}

templates/users/updateprofile.html
{% extends "base.html" %}
{% load static %}
{% block head_content %}
    <title>Update Profile</title>
{% endblock %}
<!DOCTYPE html>

{% block container %}
<div   class="container h-100">
    <div class="row h-100 justify-content-center " id="box-feed">
        <div class="col-sm-12 col-md-5 col-lg-8 ci pt-2 pl-5 pr-5 pb-5" id="auth-container">
            
            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{ error }}
                </div>
                {% endfor %}

                <div class="form-group">
                    <h4>Trained In:</h4>
                    <input
                        class="form-control"
                        type="text"
                        name="trained_in"
                        placeholder="Trained In"
                        
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>          
        </div>  
    </div>
</div>
{% endblock %}